### PR TITLE
fabricstore: Implementation of stratumn/sdk/store/AdapterV2

### LINKED ISSUE #9: Migrate to the new stratumn/sdk/store interface

### PR DESCRIPTION
**Pull request by piedup**
Implementation of the new store interface in fabricstore
* added an EvidenceStore to fabricstore to save evidences locally
* migrated chaincode from managing segments to managing links
* updated tests accordingly

Resolves #9 

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/fabricstore/13)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Gopkg.toml, line 3 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aFfBPYvKLWL2BqFxP:-L-aFfBPYvKLWL2BqFxQ:b-gey8at) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/Gopkg.toml#L3)):*
> ```TOML
> [[constraint]]
>   name = "github.com/stratumn/sdk"
>   revision = "e9fcf645dac81efb3130c9ca88eaa2d897c41b71"
> ```

Integration with goprivate merge breaks your code?

---

*[chaincode/pop/pop.go, line 251 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aGgs4oDzvuhbCg__p:-L-aGgs4oDzvuhbCg__q:berw3nq) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/chaincode/pop/pop.go#L251)):*
> ```Go
> 
> 	// Send event
> 	if err := stub.SetEvent(pc.CreateLink, byteArgs[1]); err != nil {
> ```

Why put `byteArgs[1]` and not `linkDocBytes`?

---

*[chaincode/pop/popconfig/popconfig.go, line 1 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aHJDXmUHqLCg_8jgM:-L-aHJDXmUHqLCg_8jgN:bp83ihm) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/chaincode/pop/popconfig/popconfig.go#L1)):*
> ```Go
> package popconfig
> ```

Good choice to mutualize consts.

---

*[cmd/fabricstore/main.go, line 62 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aHchpPWSZgAHJXPCT:-L-aHchpPWSZgAHJXPCU:bxs3jvi) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/cmd/fabricstore/main.go#L62)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Fatalf("Could not start locla storage: %v", err)
> ```

nit: typo

---

*[integration/docker-compose.yml, line 120 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aJ42bAkgr3lKlgA5l:-L-aJ42bAkgr3lKlgA5m:b-r63zdo) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/integration/docker-compose.yml#L120)):*
> ```YAML
>       - $GOPATH/src/github.com/stratumn/fabricstore/vendor/github.com/:/opt/gopath/src/github.com
>       - $GOPATH/src/github.com/stratumn/fabricstore/:/opt/gopath/src/github.com/stratumn/fabricstore
>       - $GOPATH/src/github.com/stratumn/fabricstore/chaincode/pop/:/opt/gopath/src/github.com/pop
> ```

Why include source directories?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Gopkg.toml, line 3 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aFfBPYvKLWL2BqFxP:-L-aJhLlkDUKQj04e8Qx:b68v92k) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/Gopkg.toml#L3)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Integration with goprivate merge breaks your code?
</blockquote></details>

No I don't think so. But since fabricstore is outside the sdk some commits in the sdk are going to break fabricstore. So I prefer using a revision and update this when releasing new code in fabricstore. This way I am sure that fabricstore master always compiles.

---

*[chaincode/pop/pop.go, line 251 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aGgs4oDzvuhbCg__p:-L-aK7o1S9IeqyyxRhT1:bv6nzex) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/chaincode/pop/pop.go#L251)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why put `byteArgs[1]` and not `linkDocBytes`?
</blockquote></details>

byteArgs[1] is a bytes version of a Link whereas linkDocBytes is a bytes version of a LinkDoc

---

*[integration/docker-compose.yml, line 120 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aJ42bAkgr3lKlgA5l:-L-aKPi_Gu0xow95qBKK:bnyjsp5) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/integration/docker-compose.yml#L120)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why include source directories?
</blockquote></details>

When launching a fabric network, the chaincode needs to be compiled and installed on each peer so we need the source files to build. I would prefer using a coiled version of the chaincode but it is not how it is documented. I will investigate to see how we could use a binary directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13)*

**Comment by piedup** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/fabricstore/main.go, line 62 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aHchpPWSZgAHJXPCT:-L-aQeuksDItsZ3hs9iK:b-896fix) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/cmd/fabricstore/main.go#L62)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Gopkg.toml, line 3 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aFfBPYvKLWL2BqFxP:-L-aLM-pNiSIFqCTfrMS:bf5ultr) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/Gopkg.toml#L3)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

No I don't think so. But since fabricstore is outside the sdk some commits in the sdk are going to break fabricstore. So I prefer using a revision and update this when releasing new code in fabricstore. This way I am sure that fabricstore master always compiles.
</blockquote></details>

Ok. It is the job of dep ensure without update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-:-L-aw4ikhucgAgEFkqtl:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[chaincode/pop/pop.go, line 41 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bcD9-qOWJcRSwvOcw:-L-bcD90da4B0avZ436B:b861lf8) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop.go#L41)):*
> ```Go
> // ObjectType used in CouchDB documents
> const (
> 	// ObjectTypeSegment = "segment"
> ```

Remove entirely (instead of commented out)?

---

*[chaincode/pop/pop.go, line 215 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bcYKtC_qpfI0dxD0N:-L-bcYKtC_qpfI0dxD0O:b-n9lof1) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop.go#L215)):*
> ```Go
> }
> 
> // CreateLink persits Link to blockchain.
> ```

nit: typo: persists

---

*[chaincode/pop/pop_test.go, line 89 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bd-SHOgOGKaMN8Dcq:-L-bd-SHOgOGKaMN8Dcr:b-ojmhvz) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop_test.go#L89)):*
> ```Go
> 	stub := shim.NewMockStub("pop", cc)
> 
> 	segment := cstesting.RandomSegment()
> ```

You can leverage the new cstesting.RandomLink() method

---

*[chaincode/pop/pop_test.go, line 92 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bd4oalrV0TlNGI5Sp:-L-bd4oalrV0TlNGI5Sq:bekn0wx) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop_test.go#L92)):*
> ```Go
> 
> 	delete(segment.Link.Meta, "prevLinkHash")
> 	segment.SetLinkHash()
> ```

This is not needed since you only work on the link (the delete is not needed either)

---

*[chaincode/pop/pop_test.go, line 110 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bdCR8mMiqnHwyhfPo:-L-bdCR8mMiqnHwyhfPp:b5b7a8q) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop_test.go#L110)):*
> ```Go
> 	res := stub.MockInvoke("1", [][]byte{[]byte(pc.GetLink), []byte(segment.GetLinkHashString())})
> 	if res.Payload != nil {
> 		fmt.Println("DeleteLink failed")
> ```

I think that you can remove the delete operation entirely from the exposed API.
Now that other stores support the new store interface, I think that fabric doesn't need to be backwards-compatible and expose the old interfaces.

---

*[chaincode/pop/popconfig/popconfig.go, line 10 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-beOEObCTCYs1F4VHN:-L-beOEPdJYS5nnIlyb8:b-rf35gc) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/popconfig/popconfig.go#L10)):*
> ```Go
> 	FindLinks   = "FindLinks"
> 	GetMapIDs   = "GetMapIDs"
> 	SaveValue   = "SaveValue"
> ```

I'm not sure fabric store should implement the keyvaluestore interface...
I don't see a scenario where we'll want consensus/validation on key-value storage, so it will probably make fabric store simpler if it doesn't implement it (and receive a key-value store based on leveldb or IPFS if it needs one for its internal details)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13)*

**Comment by piedup** [comment]
Review status: 8 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[chaincode/pop/pop.go, line 41 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bcD9-qOWJcRSwvOcw:-L-eunn1l9_M9Ycnhe72:b-896fix) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop.go#L41)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Remove entirely (instead of commented out)?
</blockquote></details>

Done.

---

*[chaincode/pop/pop.go, line 215 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bcYKtC_qpfI0dxD0N:-L-euq55ba41eCx-3NHI:b-896fix) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop.go#L215)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: typo: persists
</blockquote></details>

Done.

---

*[chaincode/pop/pop_test.go, line 89 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bd-SHOgOGKaMN8Dcq:-L-euz_7PxYHgv_O7B_9:b-896fix) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop_test.go#L89)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

You can leverage the new cstesting.RandomLink() method
</blockquote></details>

Done.

---

*[chaincode/pop/pop_test.go, line 92 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bd4oalrV0TlNGI5Sp:-L-esw7XkuspKCnVuOXJ:b-r4sjrz) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop_test.go#L92)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

This is not needed since you only work on the link (the delete is not needed either)
</blockquote></details>

I am using delete prevLinkHash to simulate this is the first Link in a Map. Chaincode creates a Map object when saving the first Link of a Map. It might be worth changing this logic in the chaincode but this is for another PR.

---

*[chaincode/pop/pop_test.go, line 110 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bdCR8mMiqnHwyhfPo:-L-etJrUwIe-WakRdT1p:b-3bskl4) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop_test.go#L110)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I think that you can remove the delete operation entirely from the exposed API.
Now that other stores support the new store interface, I think that fabric doesn't need to be backwards-compatible and expose the old interfaces.
</blockquote></details>

I agree it should be removed. However I would prefer to remove the backward compatibility in a separate PR so that we have one committed state where fabricstore supports both Adapter interfaces.

---

*[chaincode/pop/popconfig/popconfig.go, line 10 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-beOEObCTCYs1F4VHN:-L-etTZk-F3GIDwsTghc:b2nreh6) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/popconfig/popconfig.go#L10)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I'm not sure fabric store should implement the keyvaluestore interface...
I don't see a scenario where we'll want consensus/validation on key-value storage, so it will probably make fabric store simpler if it doesn't implement it (and receive a key-value store based on leveldb or IPFS if it needs one for its internal details)
</blockquote></details>

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[chaincode/pop/pop_test.go, line 110 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-bdCR8mMiqnHwyhfPo:-L-evw3fDvA_a53ZQwPg:b-hfghm4) ([raw file](https://github.com/stratumn/fabricstore/blob/95119e139b55a1321f4883272904a3530873eb84/chaincode/pop/pop_test.go#L110)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

I agree it should be removed. However I would prefer to remove the backward compatibility in a separate PR so that we have one committed state where fabricstore supports both Adapter interfaces.
</blockquote></details>

Sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-:-L-ew0WAUNlQ-FEm-zqJ:bnfp4nl)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Gopkg.toml, line 3 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-aFfBPYvKLWL2BqFxP:-L-g-tflyp7IuLCLte9L:b-mn2oe5) ([raw file](https://github.com/stratumn/fabricstore/blob/4a2cdb271408b7a0761b6b30631c69d2f42a63a2/Gopkg.toml#L3)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

No I don't think so. But since fabricstore is outside the sdk some commits in the sdk are going to break fabricstore. So I prefer using a revision and update this when releasing new code in fabricstore. This way I am sure that fabricstore master always compiles.
</blockquote></details>

Does this make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13)*

**Comment by alexppxela** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[chaincode/pop/pop_test.go, line 94 at r3](https://reviewable.io:443/reviews/stratumn/fabricstore/13#-L-g7KRNWGj4WtYMuYlW:-L-g7IQYbCkK17gLlZ5U:b-4jvn8) ([raw file](https://github.com/stratumn/fabricstore/blob/fedeea648dc5bb2b412e78eaeef9a965b4c4fb47/chaincode/pop/pop_test.go#L94)):*
> ```Go
> 	if err != nil {
> 		t.Logf(err.Error())
> 		t.FailNow()
> ```

I did not known this way to write. It's similar as `t.Fatal(err.Error())` or `t.Fatalf("%s", err)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/13)*

**Pull request merged**
