### PR TITLE
Remove old store interface

### LINKED ISSUE #14: Remove old store interface

### PR DESCRIPTION
**Pull request by alexppxela**
Resolves #14

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/fabricstore/16)

### CODE REVIEW

**Comment by piedup** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Gopkg.toml, line 3 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i0DgKu_7fJTj33x7o:-L0i0DgKu_7fJTj33x7p:b-c6m3lg) ([raw file](https://github.com/stratumn/fabricstore/blob/3a9854c3c49d62e22fb77e4c2398808a7863fe3e/Gopkg.toml#L3)):*
> ```TOML
> [[constraint]]
>   name = "github.com/stratumn/sdk"
>   revision = "e9fcf645dac81efb3130c9ca88eaa2d897c41b71"
> ```

I like to keep a revision number there to make sure that the fabricstore always compiles as there might be breaking changes in the sdk. What do you think?

---

*[.vscode/launch.json, line 2 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i0LnY1TGic-F0hGNf:-L0i0LnY1TGic-F0hGNg:b-zbt95e) ([raw file](https://github.com/stratumn/fabricstore/blob/2ebbf0bb31897c490d1128ceb16f28d0426ba472/.vscode/launch.json#L2)):*
> ```JSON
> {
>     // Utilisez IntelliSense pour en savoir plus sur les attributs possibles.
> ```

I am not sure that comment should be there.

---

*[fabricstore/fabricstore.go, line 280 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i1-og0WM8dTrJ7If7:-L0i1-og0WM8dTrJ7If8:b-gl3ghi) ([raw file](https://github.com/stratumn/fabricstore/blob/2ebbf0bb31897c490d1128ceb16f28d0426ba472/fabricstore/fabricstore.go#L280)):*
> ```Go
> 	_, err := f.channelClient.ExecuteTx(apitxn.ExecuteTxRequest{
> 		ChaincodeID: f.config.ChaincodeID,
> 		Fcn:         pc.SaveValue,
> ```

I think for consistency it would make sense to change the constants as well.

---

*[fabricstore/fabricstore_test.go, line 297 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i1vLNUD1RDva1vu1d:-L0i1vLNUD1RDva1vu1e:b3kre) ([raw file](https://github.com/stratumn/fabricstore/blob/2ebbf0bb31897c490d1128ceb16f28d0426ba472/fabricstore/fabricstore_test.go#L297)):*
> ```Go
> 		return
> 	}
> 	panic("duh")
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/16)*

**Comment by t-bast** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[fabricstore/fabricstore.go, line 342 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i5yOy7x-xlS_wBaS-:-L0i5yOy7x-xlS_wBaS0:b-1e5yg1) ([raw file](https://github.com/stratumn/fabricstore/blob/2ebbf0bb31897c490d1128ceb16f28d0426ba472/fabricstore/fabricstore.go#L342)):*
> ```Go
> 			// TODO generate new fabricstore evidence
> 			for _, c := range f.eventChans {
> 				c <- &store.Event{
> ```

You should build the event with the helper methods that store.Event offers.
There's a method to create a new SavedLinks event and add links to it (it's now a slice, not a single linl)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/16)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Gopkg.toml, line 3 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i0DgKu_7fJTj33x7o:-L0imuFYyOC6_Ulqw-tL:b968v6r) ([raw file](https://github.com/stratumn/fabricstore/blob/3a9854c3c49d62e22fb77e4c2398808a7863fe3e/Gopkg.toml#L3)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

I like to keep a revision number there to make sure that the fabricstore always compiles as there might be breaking changes in the sdk. What do you think?
</blockquote></details>

Yes I understand, I'm waiting for sdk release 0.2.0 this week.

---

*[.vscode/launch.json, line 2 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i0LnY1TGic-F0hGNf:-L0inAfnjtlLnASFEFoI:b-ia1udd) ([raw file](https://github.com/stratumn/fabricstore/blob/2ebbf0bb31897c490d1128ceb16f28d0426ba472/.vscode/launch.json#L2)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

I am not sure that comment should be there.
</blockquote></details>

I should not commit this file. It does not work at all

---

*[fabricstore/fabricstore.go, line 280 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i1-og0WM8dTrJ7If7:-L0iocl0LaXvbceYuJsB:bb74x83) ([raw file](https://github.com/stratumn/fabricstore/blob/2ebbf0bb31897c490d1128ceb16f28d0426ba472/fabricstore/fabricstore.go#L280)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

I think for consistency it would make sense to change the constants as well.
</blockquote></details>

True

---

*[fabricstore/fabricstore.go, line 342 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i5yOy7x-xlS_wBaS-:-L0iqo9Xud-KMbLWKN2P:b-c1koiv) ([raw file](https://github.com/stratumn/fabricstore/blob/2ebbf0bb31897c490d1128ceb16f28d0426ba472/fabricstore/fabricstore.go#L342)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

You should build the event with the helper methods that store.Event offers.
There's a method to create a new SavedLinks event and add links to it (it's now a slice, not a single linl)
</blockquote></details>

Ok, I'm changing SDK interface of `NewSavedLinks` function

---

*[fabricstore/fabricstore_test.go, line 297 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L0i1vLNUD1RDva1vu1d:-L0ir1N_-dXmQlqqzY3k:b-46in) ([raw file](https://github.com/stratumn/fabricstore/blob/2ebbf0bb31897c490d1128ceb16f28d0426ba472/fabricstore/fabricstore_test.go#L297)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

?
</blockquote></details>

I was for test, sorry ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/16)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-:-L0tI_3J5PryrlGlxuNW:bnfp4nl)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[Gopkg.lock, line 317 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L1Rqr6qm54X593WMW6c:-L1Rqr6qm54X593WMW6d:b1j77di) ([raw file](https://github.com/stratumn/fabricstore/blob/8cddb4147833c6bcaf942c384b7c7a701a95d534/Gopkg.lock#L317)):*
> ```
>   name = "github.com/stratumn/sdk"
>   packages = ["bufferedbatch","cs","cs/cstesting","filestore","jsonhttp","jsonws","leveldbstore","store","store/storehttp","testutil","types"]
>   revision = "master"
> ```

This doesn't work. It should be branch = "master".

---

*[fabricstore/fabricstore_test.go, line 298 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L1Rv6BNsGCqbgM4gQl8:-L1Rv6BNsGCqbgM4gQl9:b-xndp3b) ([raw file](https://github.com/stratumn/fabricstore/blob/8cddb4147833c6bcaf942c384b7c7a701a95d534/fabricstore/fabricstore_test.go#L298)):*
> ```Go
> 	fabricstore.AddStoreEventChannel(c)
> 	// Purge events
> 	for {
> ```

This will block. You don't really need to purge events as this channel was just created and no link has been created since it was created.

---

*[fabricstore/fabricstore_test.go, line 314 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-L1RztQRknEbnwco5F0r:-L1RztQRknEbnwco5F0s:bkofkq1) ([raw file](https://github.com/stratumn/fabricstore/blob/8cddb4147833c6bcaf942c384b7c7a701a95d534/fabricstore/fabricstore_test.go#L314)):*
> ```Go
> 	event := <-c
> 	assert.Equal(t, store.SavedLinks, event.EventType, "CreateLink should send a SavedLinkEvent")
> 	link, ok := event.Data.(*cs.Link)
> ```

Data is of type []*cs.Link not *cs.Link

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/16)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-:-L1S8nHcXf9Pc__02xBR:bnfp4nl)*

**Comment by piedup** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/16#-:-L1SKoaXO4o0Fi_OWaAj:bnfp4nl)*

**Pull request merged**
