### PR TITLE
Prepare release 0.2.0

### PR DESCRIPTION
**Pull request by alexppxela**
fabricinstaller docker image is now created using Makefile

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/fabricstore/24)

### CODE REVIEW

**Comment by t-bast** [comment]
:lgtm: but probably worth waiting for Pierre's input

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-:-L1qfoI_l4zlJFn2qhRy:bkzbdi2)*

**Comment by piedup** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[Makefile, line 15 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-L1qz8mpp9DzX3btjjF7:-L1qz8mpp9DzX3btjjF8:b-ehtyq2) ([raw file](https://github.com/stratumn/fabricstore/blob/72c266971e9870076bf1fa079dd30419aa30a0c3/Makefile#L15)):*
> ```Makefile
> RELEASE_NOTES_FILE=RELEASE_NOTES.md
> TEXT_FILES=LICENSE RELEASE_NOTES.md CHANGE_LOG.md
> DOCKER_USER?=indigoframework
> ```

Do we need to change the password env variable on fabricstore repo?

---

*[cmd/fabricstore/main.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-L1qzRFJ5t24M8Xq80aG:-L1qzRFJ5t24M8Xq80aH:b-7l5npo) ([raw file](https://github.com/stratumn/fabricstore/blob/72c266971e9870076bf1fa079dd30419aa30a0c3/cmd/fabricstore/main.go#L38)):*
> ```Go
> 	configFile  = flag.String("configFile", os.Getenv("CLIENT_CONFIG_PATH"), "Absolute path to network config file")
> 	path        = flag.String("path", os.Getenv("LOCALSTORAGE_PATH"), "Path used for local storage")
> 	version     = "x.y.z"
> ```

Isn't that what we display on the UI?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/fabricstore/main.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-L1qzRFJ5t24M8Xq80aG:-L1r0CdNEPme6vYh34A5:boof73i) ([raw file](https://github.com/stratumn/fabricstore/blob/72c266971e9870076bf1fa079dd30419aa30a0c3/cmd/fabricstore/main.go#L38)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Isn't that what we display on the UI?
</blockquote></details>

No, we use the version that's set in each release (we made the same change in all cmd in the SDK to make it clear)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24)*

**Comment by piedup** [comment]
*[cmd/fabricstore/main.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-L1qzRFJ5t24M8Xq80aG:-L1r0TzTMkB2dRQhgeTv:bb71j0i) ([raw file](https://github.com/stratumn/fabricstore/blob/72c266971e9870076bf1fa079dd30419aa30a0c3/cmd/fabricstore/main.go#L38)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

No, we use the version that's set in each release (we made the same change in all cmd in the SDK to make it clear)
</blockquote></details>

Ok !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24)*

**Comment by piedup** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-:-L1r42uY0lqvDamxAFga:bnfp4nl)*

**Comment by piedup** [comment]
Can we just add into the README that the fabricstore can be tested with indigo using strat and choosing option Fabric Node?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-:-L1r4OA4R0bb7dRjgEsQ:b-yzgkqd)*

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 34 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-L1rA9vUv0QRZjQDKI8Z:-L1rA9vUv0QRZjQDKI8_:b5pg8f1) ([raw file](https://github.com/stratumn/fabricstore/blob/9b3a99863dee74934bc0afbe817280ba9913f37f/README.md#L34)):*
> ```Markdown
> ---
> 
> The main goal of _fabricstore_ is to be integrated into Indigo framework suite. To use the Indigo fabric storage, please install `strat` from #stratumn/sdk to generate a new project choosing the store _Indigo's Hyperledger Fabric Node_.
> ```

nit: 
- "the Indigo framework suite"
- "To use the Indigo Fabric Store"
- "from #stratumn/sdk and generate"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24)*

**Comment by alexppxela** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 15 at r1](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-L1qz8mpp9DzX3btjjF7:-L1rD4akGgdOMIL6byj7:b-4pxxye) ([raw file](https://github.com/stratumn/fabricstore/blob/72c266971e9870076bf1fa079dd30419aa30a0c3/Makefile#L15)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Do we need to change the password env variable on fabricstore repo?
</blockquote></details>

It should work as this for Travis

---

*[README.md, line 34 at r2](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-L1rA9vUv0QRZjQDKI8Z:-L1rCoCoxl0xXUj2QNV4:b-896fix) ([raw file](https://github.com/stratumn/fabricstore/blob/9b3a99863dee74934bc0afbe817280ba9913f37f/README.md#L34)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: 
- "the Indigo framework suite"
- "To use the Indigo Fabric Store"
- "from #stratumn/sdk and generate"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24)*

**Comment by piedup** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24)*

**Comment by t-bast** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/fabricstore/24#-:-L1rQ9WL4V_c2QlQc4w-:bnfp4nl)*

**Pull request merged**
